name: Set up Node.js
description: Install Node.js and development dependencies

inputs:
  node-version:
    description: Node.js version to install
    default: "18"
  install-command:
    description: Install command to run
    default: npm ci

runs:
  using: "composite"
  steps:
    - name: "Install Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: "Install development dependencies"
      shell: bash
      run: ${{ inputs.install-command }}
