root: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:@typescript-eslint/strict"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:jsdoc/recommended-typescript-error"
  - "plugin:n/recommended"
  - "plugin:promise/recommended"
  - "plugin:sonarjs/recommended"
  - "plugin:unicorn/recommended"
  - "prettier"

parserOptions:
  project:
    - "tsconfig.eslint.json"

settings:
  import/resolver:
    typescript: true
    node: true

env:
  es2021: true
  node: true

rules:
  unicorn/prefer-top-level-await: "off"

overrides:
  - files: ["**/*.js"]
    rules:
      "@typescript-eslint/no-var-requires": "off"
      unicorn/prefer-module: "off"

  - files: ["**/__tests__/**/*"]
    rules:
      "@typescript-eslint/no-unsafe-argument": "off"
      sonarjs/no-duplicate-string: "off"
      unicorn/no-useless-undefined: "off"

  - files: ["src/action/**/*"]
    rules:
      n/no-unpublished-import: "off"

    # temporary rule overrides
    # TODO(mc, 2023-04-12): fix problems, remove overrides, and remove  --quiet
  - files: ["bin/**/*", "src/cli/**/*"]
    rules:
      n/no-process-exit: "warn"
      unicorn/no-process-exit: "warn"
      prefer-const: "warn"
      unicorn/prevent-abbreviations: "warn"
      unicorn/prefer-module: "warn"
      unicorn/prefer-top-level-await: "warn"
      "@typescript-eslint/no-floating-promises": "warn"
      "@typescript-eslint/no-unsafe-call": "warn"
      "@typescript-eslint/no-unsafe-member-access": "warn"
      "@typescript-eslint/restrict-template-expressions": "warn"
      jsdoc/require-jsdoc: "warn"
      jsdoc/require-param: "warn"
      jsdoc/require-returns: "warn"
