root: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:@typescript-eslint/strict"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:jsdoc/recommended-typescript-error"
  - "plugin:n/recommended"
  - "plugin:promise/recommended"
  - "plugin:sonarjs/recommended"
  - "plugin:unicorn/recommended"
  - "prettier"

parserOptions:
  project:
    - "tsconfig.eslint.json"

settings:
  import/resolver:
    typescript: true
    node: true

env:
  es2021: true
  node: true

rules:
  unicorn/prefer-top-level-await: "off"

overrides:
  - files: ["**/*.js"]
    rules:
      "@typescript-eslint/no-var-requires": "off"
      unicorn/prefer-module: "off"

  - files: ["**/__tests__/**/*"]
    rules:
      "@typescript-eslint/no-unsafe-argument": "off"
      "@typescript-eslint/no-unsafe-assignment": "off"
      sonarjs/no-duplicate-string: "off"
      unicorn/no-useless-undefined: "off"

  - files: ["src/action/**/*"]
    rules:
      n/no-unpublished-import: "off"
