name: NPM Publish
description: Fast, easy publishing to NPM

author: James Messinger
branding:
  color: blue
  icon: package

inputs:
  token:
    description: The NPM access token to use when publishing
    required: true

  registry:
    description: The NPM registry URL to use
    required: false

  package:
    description: The path to your package or its package.json file
    required: false

  tag:
    description: The distribution tag to publish
    required: false

  access:
    description: >
      Determines whether the published package should be publicly visible,
      or restricted to members of your NPM organization.
    required: false

  provenance:
    description: Attach provenance statements when publishing.
    required: false

  strategy:
    description: >
      Version check and release strategy.
      If "all" (default), package will be published if its version is simply not yet published.
      If "upgrade", package will be published if its version is higher than the existing tag,
      according to semantic versioning.

    required: false

  ignore-scripts:
    description: >
      Run npm with the --ignore-scripts flag as a security precaution.
      Enabled by default.
    required: false

  dry-run:
    description: Run npm with the --dry-run flag to avoid actually publishing anything.
    required: false

outputs:
  id:
    description: >
      The identifier of the published package.
      If a release was published, format is `${name}@${version}.
      If no release occurred, will be an empty string.

  type:
    description: >
      The type of version change that occurred on the published tag.
      If release was an upgrade, will be a semver release type ("major", "minor", ...).
      If the published tag had no previous version, will be "initial".
      If version was change was not an upgrade, will be "different".
      If no release occurred, will be an empty string.

  name:
    description: Name of the package.

  version:
    description: Version of the package.

  old-version:
    description: >
      The previous version on the distribution tag.
      If there was no previous version on the tag, will be an empty string.

  registry:
    description: The registry used for version checking and publishing.

  tag:
    description: The distribution tag used for version checking and publishing.

  access:
    description: >
      The package access setting used.
      If configured by the action or package.json, will be "public" or "protected".
      If not configured for a non-scoped package, will be "public".
      If not configured for a scoped package, will be "default".

runs:
  using: node20
  main: action.js
